function AdminDashboard({ queues, selectedQueueId, queueName, queueDetail, queueStats, servingToken, onSelectQueue, onQueueNameChange, onCreateQueue, onAdminAction }) {
  return (
    <div className="admin-grid">
      <section className="panel admin-sidebar"><div className="section-heading"><div><p className="eyebrow">Operations</p><h2>Queue manager</h2></div><span className="count-pill">Admin</span></div><form onSubmit={onCreateQueue} className="queue-form compact-form"><input type="text" value={queueName} onChange={(event) => onQueueNameChange(event.target.value)} placeholder="Name a new queue" required /><button type="submit" className="primary-btn">Create queue</button></form><div className="queue-list">{queues.map((queue) => <button key={queue.id} type="button" className={`queue-card ${selectedQueueId === queue.id ? 'selected' : ''}`} onClick={() => onSelectQueue(queue.id)}><div><h3>{queue.name}</h3><p>{queue.location || 'Main office'}</p></div><span className="mini-badge">{queue.status}</span></button>)}</div></section>
      <section className="panel detail-panel">{queueDetail ? <><div className="section-heading detail-header"><div><p className="eyebrow">Live operations</p><h2>{queueDetail.queue.name}</h2><p className="muted">{queueDetail.queue.location}</p></div><button type="button" className="primary-btn" onClick={() => onAdminAction(queueDetail.queue.id, 'next')}>Call next token <span>→</span></button></div><div className="summary-row"><div className="summary-box"><span>Currently serving</span><strong>{servingToken?.token_number || 'None'}</strong></div><div className="summary-box"><span>Waiting</span><strong>{queueStats.waiting}</strong></div><div className="summary-box"><span>Completed</span><strong>{queueStats.completed}</strong></div></div><div className="token-table"><div className="token-row header-row"><span>Token</span><span>Status</span><span>Actions</span></div>{queueDetail.tokens.map((token) => <div key={token.id} className="token-row"><span>{token.token_number}</span><span className={`status-badge ${token.status.toLowerCase()}`}>{token.status}</span><div className="action-group">{token.status !== 'COMPLETED' && <button type="button" className="small-btn" onClick={() => onAdminAction(queueDetail.queue.id, 'complete', token.id)}>Complete</button>}{token.status !== 'SKIPPED' && <button type="button" className="small-btn danger" onClick={() => onAdminAction(queueDetail.queue.id, 'skip', token.id)}>Skip</button>}</div></div>)}</div></> : <div className="empty-state">Select a queue to view live details.</div>}</section>
    </div>
  );
}

export default AdminDashboard;
