import { useEffect, useState } from 'react';
import API from './api';
import AdminDashboard from './components/AdminDashboard';
import AuthScreen from './components/AuthScreen';
import UserDashboard from './components/UserDashboard';

const emptyForm = { name: '', email: '', password: '', role: 'user', department_id: '' };

function App() {
  const [authMode, setAuthMode] = useState('login');
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [user, setUser] = useState(null);
  const [formData, setFormData] = useState(emptyForm);
  const [queueName, setQueueName] = useState('');
  const [queues, setQueues] = useState([]);
  const [selectedQueueId, setSelectedQueueId] = useState(null);
  const [queueDetail, setQueueDetail] = useState(null);
  const [activeTicket, setActiveTicket] = useState(null);
  const [activeTickets, setActiveTickets] = useState([]);
  const [ticketHistory, setTicketHistory] = useState([]);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const isAdmin = user?.role === 'admin';

  const loadQueues = async () => {
    const response = await API.get('/queues');
    const nextQueues = response.data.queues || [];
    setQueues(nextQueues);
    setSelectedQueueId((current) => nextQueues.some((queue) => queue.id === current) ? current : nextQueues[0]?.id || null);
  };

  const loadQueueDetail = async (queueId) => {
    if (!queueId) return;
    const response = await API.get(`/queues/${queueId}`);
    setQueueDetail(response.data);
  };

  const loadMyTickets = async () => {
    if (isAdmin) return;
    const response = await API.get('/queues/mine');
    setActiveTicket(response.data.active_ticket);
    setActiveTickets(response.data.active_tickets || []);
    setTicketHistory(response.data.history || []);
  };

  const refreshData = async () => {
    try {
      await loadQueues();
      await loadMyTickets();
    } catch (requestError) {
      console.error('Failed to refresh QueueX data', requestError);
    }
  };

  useEffect(() => {
    const token = localStorage.getItem('queuexToken');
    if (!token) return;
    API.get('/auth/me').then((response) => {
      setUser(response.data.user);
      setIsLoggedIn(true);
    }).catch(() => {
      localStorage.removeItem('queuexToken');
    });
  }, []);

  useEffect(() => {
    if (isLoggedIn) refreshData();
  }, [isLoggedIn, isAdmin]);

  useEffect(() => {
    if (!isLoggedIn || isAdmin) return undefined;
    const refreshTimer = window.setInterval(loadMyTickets, 8000);
    return () => window.clearInterval(refreshTimer);
  }, [isLoggedIn, isAdmin]);

  useEffect(() => {
    if (selectedQueueId) loadQueueDetail(selectedQueueId).catch(() => setError('Could not load queue details'));
  }, [selectedQueueId]);

  const handleAuth = async (event) => {
    event.preventDefault();
    setError('');
    try {
      const endpoint = authMode === 'login' ? '/auth/login' : '/auth/register';
      const payload = authMode === 'login' ? { email: formData.email, password: formData.password } : formData;
      const response = await API.post(endpoint, payload);
      localStorage.setItem('queuexToken', response.data.token);
      setUser(response.data.user);
      setIsLoggedIn(true);
      setFormData(emptyForm);
      setMessage(authMode === 'login' ? 'Welcome back.' : 'Account created successfully.');
    } catch (requestError) {
      setError(requestError.response?.data?.message || 'Authentication failed');
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('queuexToken');
    setIsLoggedIn(false);
    setUser(null);
    setActiveTicket(null);
    setActiveTickets([]);
    setTicketHistory([]);
    setMessage('You have been logged out.');
  };

  const handleJoinQueue = async (queueId) => {
    setError('');
    try {
      const response = await API.post(`/queues/${queueId}/join`);
      setActiveTicket({ ...response.data.token, ...response.data, queue_id: queueId });
      setMessage(`You're in. Your token is ${response.data.token.token_number}.`);
      await Promise.all([loadQueueDetail(queueId), refreshData()]);
    } catch (requestError) {
      setError(requestError.response?.data?.message || 'Could not join this queue');
    }
  };

  const handleCreateQueue = async (event) => {
    event.preventDefault();
    try {
      await API.post('/queues', { name: queueName, description: 'Virtual queue generated by QueueX', location: 'Main Office', average_service_time: 5 });
      setQueueName('');
      setMessage('Queue created successfully.');
      await loadQueues();
    } catch (requestError) {
      setError(requestError.response?.data?.message || 'Could not create queue');
    }
  };

  const handleAdminAction = async (queueId, action, tokenId) => {
    try {
      const endpoint = action === 'next' ? `/queues/${queueId}/next` : `/queues/${queueId}/tokens/${tokenId}/${action}`;
      const response = await API.post(endpoint);
      setMessage(response.data.message || `Token ${action}ed successfully.`);
      await Promise.all([loadQueueDetail(queueId), loadQueues()]);
    } catch (requestError) {
      setError(requestError.response?.data?.message || 'Queue action failed');
    }
  };

  if (!isLoggedIn) {
    return <AuthScreen authMode={authMode} formData={formData} message={message} error={error} onModeChange={setAuthMode} onChange={(event) => setFormData((current) => ({ ...current, [event.target.name]: event.target.value }))} onSubmit={handleAuth} />;
  }

  const waitingTokens = queueDetail?.tokens?.filter((token) => token.status === 'WAITING') || [];
  const queueStats = { total: queueDetail?.tokens?.length || 0, waiting: waitingTokens.length, serving: queueDetail?.tokens?.filter((token) => token.status === 'SERVING').length || 0, completed: queueDetail?.tokens?.filter((token) => token.status === 'COMPLETED').length || 0, skipped: queueDetail?.tokens?.filter((token) => token.status === 'SKIPPED').length || 0 };
  const servingToken = queueDetail?.tokens?.find((token) => token.status === 'SERVING');

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="topbar-brand"><div className="brand-icon">QX</div><div><strong>QueueX</strong><span>{isAdmin ? 'Operations console' : 'Your place in line'}</span></div></div>
        <div className="topbar-user"><div className="avatar">{user?.name?.slice(0, 1).toUpperCase()}</div><div className="user-meta"><strong>{user?.name}</strong><span>{isAdmin ? 'Administrator' : 'Member'}</span></div><button className="secondary-btn" onClick={handleLogout}>Log out</button></div>
      </header>
      <main className="dashboard-page">
        {(message || error) && <div className={error ? 'error-box alert' : 'success-box alert'}>{error || message}</div>}
        {isAdmin ? <AdminDashboard queues={queues} selectedQueueId={selectedQueueId} queueName={queueName} queueDetail={queueDetail} queueStats={queueStats} servingToken={servingToken} onSelectQueue={setSelectedQueueId} onQueueNameChange={setQueueName} onCreateQueue={handleCreateQueue} onAdminAction={handleAdminAction} /> : <UserDashboard user={user} queues={queues} activeTicket={activeTicket} activeTickets={activeTickets} history={ticketHistory} queueDetail={queueDetail} onJoinQueue={handleJoinQueue} onSelectQueue={setSelectedQueueId} />}
      </main>
    </div>
  );
}

export default App;
